language: cpp
os: linux
compiler: gcc

addons:
    apt:
        packages: 
            - libboost-all-dev
            - lcov
            - cppcheck

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo pip install codecov
    
before_script:
    - curl -OL https://github.com/danmar/cppcheck/archive/1.90.tar.gz
    - tar -xvf 1.90.tar.gz
    - cd cppcheck-1.90
    - sudo make install FILESDIR=/usr/share/cppcheck
    - cd ..
  
script:
    - ./configure
    - cd ./build
    - cmake --build .
    - ctest --output-on-failure
    - cppcheck --version
    - ../.ci/travis-cppcheck ../.ci/suppressions.list

after_success:
    - codecov